name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Compose images
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Check running containers
        run: docker ps

      - name: Stop containers
        run: docker compose down